import type { Campaign, OptimizationAction, AnomalyAlert, AutomationRule } from "./types";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    platform: "google",
    name: "Brand Search — India",
    status: "Active",
    budget_daily: 5000,
    budget_total: 150000,
    spend: 98400,
    impressions: 284000,
    clicks: 8900,
    ctr: 3.13,
    cpc: 11.06,
    conversions: 412,
    cpa: 238.8,
    roas: 4.2,
    quality_score: 87,
    start_date: "2026-04-01",
    objective: "Conversions",
    type: "Search",
  },
  {
    id: "c2",
    platform: "linkedin",
    name: "SaaS Decision Makers",
    status: "Active",
    budget_daily: 8000,
    budget_total: 240000,
    spend: 142000,
    impressions: 98000,
    clicks: 2340,
    ctr: 2.39,
    cpc: 60.68,
    conversions: 156,
    cpa: 910.26,
    roas: 2.8,
    quality_score: 72,
    start_date: "2026-04-05",
    objective: "Lead Generation",
    type: "Sponsored Content",
  },
  {
    id: "c3",
    platform: "google",
    name: "Competitor Keywords",
    status: "Paused",
    budget_daily: 3000,
    budget_total: 90000,
    spend: 34200,
    impressions: 112000,
    clicks: 3200,
    ctr: 2.86,
    cpc: 10.69,
    conversions: 98,
    cpa: 348.98,
    roas: 2.1,
    quality_score: 54,
    start_date: "2026-03-15",
    objective: "Conversions",
    type: "Search",
  },
  {
    id: "c4",
    platform: "linkedin",
    name: "CTO Retargeting — Tier 1",
    status: "Active",
    budget_daily: 6000,
    budget_total: 180000,
    spend: 87600,
    impressions: 54000,
    clicks: 1890,
    ctr: 3.5,
    cpc: 46.35,
    conversions: 210,
    cpa: 417.14,
    roas: 3.4,
    quality_score: 78,
    start_date: "2026-04-10",
    objective: "Website Visits",
    type: "Sponsored InMail",
  },
  {
    id: "c5",
    platform: "google",
    name: "Performance Max — E-Commerce",
    status: "Active",
    budget_daily: 10000,
    budget_total: 300000,
    spend: 198000,
    impressions: 560000,
    clicks: 14200,
    ctr: 2.54,
    cpc: 13.94,
    conversions: 680,
    cpa: 291.18,
    roas: 5.1,
    quality_score: 91,
    start_date: "2026-03-20",
    objective: "Conversions",
    type: "Performance Max",
  },
];

export const MOCK_OPTIMIZATIONS: OptimizationAction[] = [
  {
    id: "o1",
    campaign_id: "c1",
    campaign_name: "Brand Search — India",
    platform: "google",
    type: "Negative Keywords",
    description: "Auto-added 28 irrelevant search terms to negatives. Reduces wasted spend by est. ₹4,200/month. (Bid change < 20%)",
    impact: "Low",
    estimated_improvement: "-₹4.2K wasted spend",
    risk: "LOW",
    approval_status: "approved",
    created_at: "2026-05-25T10:42:00Z",
    auto_apply: true,
  },
  {
    id: "o2",
    campaign_id: "c3",
    campaign_name: "Competitor Keywords",
    platform: "google",
    type: "Bid Adjustment",
    description: "Increased bids for top 12 converting keywords by 18%. Applied with 2-hour undo window. (Bid change 20–50%)",
    impact: "Medium",
    estimated_improvement: "+22% conversions",
    risk: "MEDIUM",
    approval_status: "approved",
    created_at: "2026-05-25T09:14:00Z",
    auto_apply: true,
  },
  {
    id: "o3",
    campaign_id: "c5",
    campaign_name: "Performance Max — E-Commerce",
    platform: "google",
    type: "Budget Reallocation",
    description: "Shift ₹15,000/day (32% of budget) from Display to Search — projected ROAS lift 5.1→5.8. Requires approval. (Budget change > 25%)",
    impact: "High",
    estimated_improvement: "+₹48K monthly revenue",
    risk: "HIGH",
    approval_status: "pending",
    created_at: "2026-05-25T09:15:00Z",
    auto_apply: false,
  },
  {
    id: "o4",
    campaign_id: "c2",
    campaign_name: "SaaS Decision Makers",
    platform: "linkedin",
    type: "Audience Expansion",
    description: "Pause campaign entirely and reallocate budget to Google Search — LinkedIn ROAS below 1.5x for 14 days. Requires 2-person approval. (Campaign-level action)",
    impact: "Critical",
    estimated_improvement: "+₹82K projected ROAS gain",
    risk: "CRITICAL",
    approval_status: "pending",
    created_at: "2026-05-25T08:00:00Z",
    auto_apply: false,
  },
];

export const MOCK_ALERTS: AnomalyAlert[] = [
  {
    id: "a1",
    campaign_id: "c3",
    campaign_name: "Competitor Keywords",
    platform: "google",
    type: "drop",
    metric: "CTR",
    description: "CTR dropped 42% in last 4 hours — from 2.86% to 1.64%. Possible Quality Score degradation.",
    severity: "critical",
    detected_at: "2026-05-25T06:15:00Z",
    resolved: false,
  },
  {
    id: "a2",
    campaign_id: "c2",
    campaign_name: "SaaS Decision Makers",
    platform: "linkedin",
    type: "budget",
    metric: "Daily Budget",
    description: "On pace to exhaust daily budget 3 hours early at current spend rate.",
    severity: "warning",
    detected_at: "2026-05-25T10:00:00Z",
    resolved: false,
  },
  {
    id: "a3",
    campaign_id: "c5",
    campaign_name: "Performance Max — E-Commerce",
    platform: "google",
    type: "spike",
    metric: "Conversion Rate",
    description: "CVR spiked 28% — possible tracking anomaly or genuine uplift from landing page test.",
    severity: "info",
    detected_at: "2026-05-25T09:45:00Z",
    resolved: false,
  },
];

export const ACTIVITY_LOG = [
  { id: "al1", timestamp: "2026-05-25T10:15:00Z", rule: "GA-002 Bid Reduction on High CPA", trigger: "CPA > 150% target for 7 days", action: "Reduced Target CPA by 15% on 'Competitor Keywords'", outcome: "CPA dropped from ₹483 → ₹412 in 24h", impact: "Medium", platform: "google" },
  { id: "al2", timestamp: "2026-05-25T09:00:00Z", rule: "GA-007 Budget Pacing Alert", trigger: "Projected to exceed monthly budget by 6%", action: "Reduced daily budget on all campaigns by 8%", outcome: "Spend rate normalised", impact: "Low", platform: "google" },
  { id: "al3", timestamp: "2026-05-25T08:30:00Z", rule: "LI-001 LinkedIn Low CTR Creative Refresh", trigger: "CTR < 0.35% for 7 days on 'SaaS Decision Makers'", action: "3 new ad variants generated via AI Creative Engine", outcome: "Pending — test started", impact: "Medium", platform: "linkedin" },
  { id: "al4", timestamp: "2026-05-24T18:00:00Z", rule: "GA-004 Negative Keyword Auto-Add", trigger: "Search term 'free ads' spent ₹840 with 0 conversions", action: "Added 'free ads' as negative exact match", outcome: "₹840/month wasted spend prevented", impact: "Low", platform: "google" },
  { id: "al5", timestamp: "2026-05-24T15:30:00Z", rule: "GA-003 Bid Increase on Low CPA", trigger: "CPA < 70% target AND 14 conversions in 7 days", action: "Increased Target CPA by 10% on 'Brand Search — India'", outcome: "Conversions +12% in following 48h", impact: "Low", platform: "google" },
  { id: "al6", timestamp: "2026-05-24T12:00:00Z", rule: "XC-002 Anomaly Alert", trigger: "CTR deviated 3σ from 30-day mean on Competitor Keywords", action: "Alert sent to Slack + email. Root cause analysis triggered.", outcome: "Identified: competitor outbidding on brand terms", impact: "High", platform: "google" },
];

export const MOCK_AUTOMATIONS: AutomationRule[] = [
  {
    id: "r1",
    name: "Pause Low-Quality Keywords",
    description: "Auto-pause keywords with Quality Score < 3 and > 200 impressions",
    trigger: "QS < 3 AND impressions > 200",
    action: "Pause keyword + notify",
    platform: "google",
    category: "Quality Control",
    enabled: true,
    last_triggered: "2026-05-24T14:30:00Z",
    executions: 47,
  },
  {
    id: "r2",
    name: "Budget Pacing Guard",
    description: "Reduce bids 20% when daily spend exceeds 85% of budget before 6pm",
    trigger: "spend > 85% daily budget before 18:00",
    action: "Reduce all bids by 20%",
    platform: "both",
    category: "Budget Control",
    enabled: true,
    last_triggered: "2026-05-25T10:00:00Z",
    executions: 123,
  },
  {
    id: "r3",
    name: "High-Intent Bid Boost",
    description: "Increase bids 30% for search terms containing 'buy', 'price', 'demo', 'trial'",
    trigger: "keyword intent_signal = high",
    action: "Bid +30% for 6-hour window",
    platform: "google",
    category: "Bid Strategy",
    enabled: true,
    last_triggered: "2026-05-25T08:00:00Z",
    executions: 312,
  },
  {
    id: "r4",
    name: "LinkedIn InMail Frequency Cap",
    description: "Exclude users who received InMail in last 30 days to reduce fatigue",
    trigger: "user received InMail < 30 days ago",
    action: "Add to exclusion list",
    platform: "linkedin",
    category: "Audience Management",
    enabled: true,
    last_triggered: "2026-05-23T09:00:00Z",
    executions: 28,
  },
  {
    id: "r5",
    name: "ROAS-Based Budget Scaler",
    description: "Increase budget 15% for campaigns maintaining ROAS > 4 for 3 consecutive days",
    trigger: "ROAS > 4 for 3 days",
    action: "Budget +15% (max 2x original)",
    platform: "both",
    category: "Budget Control",
    enabled: false,
    executions: 0,
  },
  {
    id: "r6",
    name: "Weekend Bid Reduction",
    description: "Reduce B2B LinkedIn bids 40% on weekends when decision-makers are offline",
    trigger: "day = Saturday OR Sunday",
    action: "Bids -40% on LinkedIn campaigns",
    platform: "linkedin",
    category: "Scheduling",
    enabled: true,
    last_triggered: "2026-05-24T00:00:00Z",
    executions: 86,
  },
  // PDF Section 10 — Official named workflows
  { id: "GA-001", name: "Underperforming Ad Pause", description: "Pause ad and generate AI replacement when CTR < 50% of ad group avg for 14 days AND Impressions > 500", trigger: "CTR < 50% of ad group avg for 14 days AND impressions > 500", action: "Pause ad. Generate replacement via AI Creative Engine.", platform: "google", category: "Quality Control", enabled: true, last_triggered: "2026-05-24T09:00:00Z", executions: 18 },
  { id: "GA-002", name: "Bid Reduction on High CPA", description: "Reduce CPC/Target CPA 15% when CPA > 150% of target for 7 consecutive days", trigger: "CPA > 150% of target for 7 consecutive days", action: "Reduce CPC/Target CPA by 15%. Alert manager.", platform: "google", category: "Bid Strategy", enabled: true, last_triggered: "2026-05-25T10:15:00Z", executions: 34 },
  { id: "GA-003", name: "Bid Increase on Low CPA", description: "Increase bid 10% when CPA < 70% of target for 7 days AND Conversions > 10", trigger: "CPA < 70% of target for 7 days AND conversions > 10", action: "Increase bid / Target CPA by 10%.", platform: "google", category: "Bid Strategy", enabled: true, last_triggered: "2026-05-24T15:30:00Z", executions: 22 },
  { id: "GA-004", name: "Negative Keyword Auto-Add", description: "Auto-add search term as negative exact match when spend > 1.5x CPA target and 0 conversions", trigger: "Search term: spend > 1.5x CPA target AND conversions = 0", action: "Add as negative exact match. Log reason.", platform: "google", category: "Quality Control", enabled: true, last_triggered: "2026-05-24T18:00:00Z", executions: 147 },
  { id: "GA-005", name: "Ad Schedule Optimisation", description: "Update ad schedule bid adjustments when CVR by hour changes significantly (statistical significance)", trigger: "CVR by hour changes significantly (stat sig)", action: "Update ad schedule bid adjustments.", platform: "google", category: "Scheduling", enabled: true, executions: 8 },
  { id: "GA-006", name: "Quality Score Emergency", description: "Pause keyword and trigger copy + landing page review when QS drops to < 4 for 3+ days", trigger: "QS drops to < 4 for 3+ days", action: "Pause keyword. Trigger copy + LP review. Alert.", platform: "google", category: "Quality Control", enabled: true, last_triggered: "2026-05-23T11:00:00Z", executions: 12 },
  { id: "GA-007", name: "Budget Pacing Alert", description: "Reduce daily budgets proportionally when projected to exceed monthly budget by > 5%", trigger: "Projected to exceed monthly budget by > 5%", action: "Reduce daily budgets proportionally. Alert finance.", platform: "google", category: "Budget Control", enabled: true, last_triggered: "2026-05-25T09:00:00Z", executions: 9 },
  { id: "GA-008", name: "Smart Bidding Ramp", description: "Migrate from Enhanced CPC to Target CPA when conversions in last 30 days cross 50 threshold", trigger: "Conversions in last 30 days cross 50 threshold", action: "Migrate from Enhanced CPC to Target CPA.", platform: "google", category: "Bid Strategy", enabled: true, last_triggered: "2026-04-15T00:00:00Z", executions: 2 },
  { id: "LI-001", name: "LinkedIn Low CTR Creative Refresh", description: "Generate 3 new ad variants and A/B test when CTR < 0.35% for 7 days AND Impressions > 1000", trigger: "CTR < 0.35% for 7 days AND Impressions > 1000", action: "Generate 3 new ad variants. A/B test.", platform: "linkedin", category: "Quality Control", enabled: true, last_triggered: "2026-05-25T08:30:00Z", executions: 7 },
  { id: "LI-002", name: "Audience Expansion Trigger", description: "Activate lookalike audience and reduce bid 10% when Frequency > 4/member/week AND CVR not improved", trigger: "Frequency > 4/member/week AND CVR not improved", action: "Activate lookalike audience. Reduce bid by 10%.", platform: "linkedin", category: "Audience Management", enabled: true, executions: 5 },
  { id: "LI-003", name: "LinkedIn Lead Quality Alert", description: "Tighten targeting when lead ICP score < 40 for > 50% of leads in 7 days", trigger: "Lead ICP score < 40 for > 50% of leads in 7 days", action: "Tighten targeting: remove lowest-quality seniority level. Alert sales.", platform: "linkedin", category: "Audience Management", enabled: true, executions: 3 },
  { id: "LI-004", name: "CPL Spike Response", description: "Narrow targeting to top 3 performing segments when CPL > 2x target for 5 days", trigger: "CPL > 2x target for 5 days", action: "Narrow targeting to top 3 performing segments. Pause bottom 20%.", platform: "linkedin", category: "Bid Strategy", enabled: true, last_triggered: "2026-05-20T00:00:00Z", executions: 4 },
  { id: "XC-001", name: "Cross-Channel Reallocation", description: "Flag reallocation recommendation for human approval when Google ROAS > 4x AND LinkedIn ROAS < 1.5x for 14 days", trigger: "Google ROAS > 4x AND LinkedIn ROAS < 1.5x for 14 days", action: "Flag reallocation recommendation for human approval.", platform: "both", category: "Budget Control", enabled: true, executions: 1 },
  { id: "XC-002", name: "Anomaly Alert — All Platforms", description: "Send immediate Slack + email alert and generate root cause report when any metric deviates > 3σ from 30-day mean", trigger: "Any metric deviates > 3σ from 30-day mean", action: "Immediate Slack + email alert. Root cause report generated.", platform: "both", category: "Quality Control", enabled: true, last_triggered: "2026-05-24T12:00:00Z", executions: 6 },
];

export const WEEKLY_SPEND = [
  { week: "W1", google: 42000, linkedin: 38000 },
  { week: "W2", google: 55000, linkedin: 44000 },
  { week: "W3", google: 61000, linkedin: 48000 },
  { week: "W4", google: 58000, linkedin: 52000 },
  { week: "W5", google: 72000, linkedin: 56000 },
  { week: "W6", google: 68000, linkedin: 60000 },
];

export const DAILY_CONVERSIONS = [
  { day: "Mon", google: 68, linkedin: 32 },
  { day: "Tue", google: 72, linkedin: 38 },
  { day: "Wed", google: 81, linkedin: 42 },
  { day: "Thu", google: 76, linkedin: 36 },
  { day: "Fri", google: 90, linkedin: 44 },
  { day: "Sat", google: 45, linkedin: 18 },
  { day: "Sun", google: 38, linkedin: 12 },
];

export const ATTRIBUTION_DATA = [
  { channel: "Google Search", conversions: 412, revenue: 1648000, share: 38 },
  { channel: "Google PMax", conversions: 280, revenue: 1428000, share: 26 },
  { channel: "LinkedIn Sponsored", conversions: 156, revenue: 780000, share: 14 },
  { channel: "LinkedIn InMail", conversions: 210, revenue: 1050000, share: 19 },
  { channel: "Direct", conversions: 32, revenue: 160000, share: 3 },
];
